version: 2.0
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run:
          name: Build dockers
          command: docker-compose build
      - run:
          name: Run tests
          command: docker-compose run --rm cli go test ./pkg/tag
workflows:
  version: 2
  build:
    jobs:
      - tests:
          context: github-robot
